[[intermediate-messages]]
== Intermediate Messages

The simulator starts a new <<scenarios,scenario>> instance for each incoming request based on the defined <<scenario-mapper,scenario mapping>>.
Sometimes a running scenario instance needs to receive another incoming request.
In such cases, the simulator handles the process differently, as the incoming request should not trigger a new scenario instance but should be forwarded to the running scenario.

This process is referred to as intermediate message handling within scenarios.
A scenario can activate message correlation for specific requests.
Before initiating a new scenario, the simulator always checks all running scenarios for matches with intermediate message correlations.
This allows us to receive additional incoming requests within the same scenario instance.

To explain this concept, consider the following simple example.

[source,java]
----
@Scenario("GoodNight")
public class GoodNightScenario extends AbstractSimulatorScenario {

    private static final String CORRELATION_ID = "x-correlationid";

    @Override
    public void run(ScenarioRunner scenario) {
        scenario.$(scenario.http()
            .receive()
            .post()
            .message()
            .body("<GoodNight xmlns=\"http://citrusframework.org/schemas/hello\">" +
                    "Go to sleep!" +
                "</GoodNight>")
            .extract(fromHeaders().header(CORRELATION_ID, "correlationId")
            ));

        scenario.$(correlation().start()
            .onHeader(CORRELATION_ID, "${correlationId}")
        );

        scenario.$(scenario.http()
            .send()
            .response(HttpStatus.OK)
            .message()
            .body("<GoodNightResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                    "Good Night!" +
                "</GoodNightResponse>"));

        scenario.$(scenario.http()
            .receive()
            .post()
            .selector("x-correlationid = '1${correlationId}'")
            .message()
            .body("<InterveningRequest>In between!</InterveningRequest>"));

        scenario.$(scenario.http()
            .send()
            .response(HttpStatus.OK)
            .message()
            .body("<InterveningResponse>In between!</InterveningResponse>"));
    }
}
----

In the scenario above, a new correlation starts on the header entry `X-CorrelationId` and the variable value `${correlationId}` extracted from the first request.
This allows the scenario to receive further incoming request messages with the correlation identifier, ensuring it receives the specific message first, before any other running scenarios.

This mechanism enables a scenario instance to handle more than one incoming request.
Message correlation can be based on header values or XPath expressions evaluated within the message payload.

[source,java]
----
@Scenario("FaxCancelled")
public class FaxCancelledScenario extends AbstractFaxScenario {

    public static final String ROOT_ELEMENT_XPATH = "string:local-name(/*)";
    public static final String REFERENCE_ID_XPATH = "//fax:referenceId";
    public static final String REFERENCE_ID_VAR = "referenceId";
    public static final String REFERENCE_ID_PH = "${referenceId}";

    @Override
    public void run(ScenarioRunner scenario) {
        scenario.$(scenario.receive()
            .message()
            .validate(xpath().expression(ROOT_ELEMENT_XPATH, "SendFaxMessage"))
            .extract(
                fromBody().expression(REFERENCE_ID_XPATH, REFERENCE_ID_VAR)));

        scenario.$(correlation().start()
            .onPayload(REFERENCE_ID_XPATH, REFERENCE_ID_PH));

        scenario.$(send()
            .endpoint(getStatusEndpoint())
            .message()
            .body(
                new MarshallingPayloadBuilder(
                    getPayloadHelper().generateFaxStatusMessage(
                        REFERENCE_ID_PH,
                        "QUEUED",
                        "The fax message has been queued and will be send shortly"
                    ),
                    getPayloadHelper().getMarshaller())
            ));

        scenario.$(scenario.receive()
            .message()
            .validate(xpath()
                .expression(ROOT_ELEMENT_XPATH, "CancelFaxMessage")
                .expression(REFERENCE_ID_XPATH, REFERENCE_ID_PH)));

        scenario.$(send()
            .endpoint(getStatusEndpoint())
            .message()
            .body(
                new MarshallingPayloadBuilder(
                    getPayloadHelper().generateFaxStatusMessage(
                        REFERENCE_ID_PH,
                        "CANCELLED",
                        "The fax message has been cancelled"
                    ),
                    getPayloadHelper().getMarshaller())
            ));
    }
}
----

The above example uses XPath expressions to establish a new correlation within the scenario.
This ensures that the second incoming request `CancelFaxMessage` is directed to the same scenario instance.

Intermediate message handling enables the creation of complex scenarios that involve multiple request-response interactions.
Message correlation ensures that the relevant requests are processed within the same scenario, without interference from other concurrent scenarios.
