[Introduction]
= Introduction

The Citrus Framework Simulator is a comprehensive tool that allows for the simulation of various messaging transports including HTTP REST, SOAP WebService, JMS, RMI, mail messaging, and more.
This simulator stands out with its robust server APIs that interact with client requests, delivering predefined messages tailored to specific scenarios.
The power of the simulator’s response logic cannot be overstated; it is designed to emulate any server interface effortlessly.

[[citrus-spring-boot-simulator]]
== Citrus Spring-Boot Simulator

Utilizing the synergy of https://projects.spring.io/spring-boot/[Spring Boot^] and the https://citrusframework.org[Citrus^] testing framework, the `citrus-spring-boot-simulator` empowers you to craft your simulator scenarios using either Java or XML.
Each interaction with the simulator is logged in an internal database, accessible for review through the REST API or the web UI.
We welcome your feedback and contributions with great appreciation!

[[project-status]]
== Project Status

We are proud to announce that the simulator application is stable and reliable for general use.
However, it is important to note that certain experimental features are included as part of our commitment to innovation.
These features are introduced with "feature flags" and are still in the developmental phase:

.Experimental Features

*WSDL Generated Scenarios*: Automatically create simulator scenarios from a WSDL file.

*Swagger Generated Scenarios*: Automatically create simulator scenarios from a Swagger API file.

These features are evolving, and with the valuable insights we receive from our community, we are optimistic that they will achieve stability in due course.

[[prerequisites]]
== Prerequisites

Before embarking on your journey with the simulator application, ensure you meet the following prerequisites:

[[limitations-java-17]]
=== Java 17

The simulator is built with Java 17 and is compatible with versions up to Java 21.
As such, Java 17 or later must be installed on your machine.
Confirm that your Java Development Kit (JDK) is properly installed and configured with the following command in a new terminal window:

[source,bash]
----
java -version
----

[[browser-compatibility]]
=== Browser Compatibility

The simulator boasts a compact web interface that springs to life upon startup.
You can access it on the root URL of your simulator application.

The `citrus-simulator-ui` module enriches this experience further with a sophisticated https://angular.io/[Angular^]-based application.
This UI is best accessed through a web browser .
It’s important to note that we do not perform cross-browser testing during our pipeline.
Thus, we cannot guarantee compatibility in all browsers.
Development and testing are primarily done on Chrome and Firefox, which are likely to yield the best experience.
