[[introduction]]
= Introduction

This is a standalone simulator for different messaging transports such as Http REST, SOAP WebService,
JMS, RMI, mail messaging and more.

The simulator provides server APIs for clients and responds with predefined messages according to
defined scenarios. The simulator response logic is very powerful and enables us to simulate any kind of server interface.

The simulator uses link:https://projects.spring.io/spring-boot/[Spring Boot] in combination with the test framework link:https://www.citrusframework.org[Citrus]. You can
code simulator scenarios in Java or XML. Each scenario execution on the simulator is stored to an internal database and can be reviewed via web UI in the browser.

Feedback and contributions are highly appreciated!

[[project-status]]
== Project status

*NOTE:* _This project is considered stable but still under construction!_

The simulator application is stable not yet finished. Some features are still under construction. Some aspects are simply not covered yet. Please see the following experimental
features.

.Experimental features
[horizontal]
WSDL generated scenarios:: Auto generate simulator scenarios from WSDL file
Swagger generated scenarios:: Auto generate simulator scenarios from Swagger API file
Combined simulator:: Use multiple message transports in one simulator instance

Following from that we have to deal with some limitations and trade offs until the project emerges (hopefully with the help of the community, keeping our fingers crossed!).
However the simulator is usable and all main features are considered to be stable.

[[project-prerequisites]]
== Prerequisites

You may want to check the following prerequisites for using the simulator application.

[[limitations-java-8]]
=== Java 8

The simulator is a Java application coded in Java 8. Following from that you need at least Java 8 to run it as a Spring Boot web application.
Please make sure that you have Java development kit installed and set up. You can verify this with this command in a new terminal window.

[source,bash]
----
java -version
----

[[limitations-browser]]
=== Browser

The simulator provides a small web user interface when started. You can access this web UI with your browser. As we are in an early state in this project we do not
invest much time in full cross-browser compatibility. We use Chrome and Firefox during development. So the simulator application is most likely to be 100% working
on these two browsers. Of course other browsers might work without any limitations, too.
