[[rest-api]]
== REST API

The simulator offers a comprehensive REST API for interacting with system entities.
The following resources are available:

* `/api/messages`
* `/api/message-headers`
* `/api/scenario-actions`
* `/api/scenario-executions`
* `/api/scenario-parameters`
* `/api/test-parameters`
* `/api/test-results`

For each listed resource, the following operations are supported:

* Listing all entries with a `GET` request to the root URI.
** Pagination and filtering are supported.
* Counting all entries with a `GET /count` endpoint.
** Note that the `?distinct=true` query parameter is required to count unique results.
* Retrieving a single resource using the `GET /{id}` endpoint.

All REST resources adhere to this pattern, with exceptions noted in subsequent sections.

The endpoint `/api/test-results` additionally supports the `DELETE` request that removes all recorded Test Results and Executions.

[[receive-single-test-result]]
=== Receive SINGLE Test-Parameter

A `TestParameter` is uniquely identified by a composite key, consisting of the `TestResult` ID and the `TestParameter` key.
To retrieve a single `TestParameter`, use the `GET /api/test-parameters/{testResultId}/{key}` endpoint. all recorded Test Results and Executions.

[[receive-scenario-execution-details]]
=== Receive Scenario Execution with Details

The `ScenarioExecution` is also unique in regard to the amount of details that _could_ be extracted from it.
However, more information (almost) always comes at the cost of performance.
Thus, the `/api/scenario-executions` endpoint offers four unique boolean query parameters:

* `includeActions`: When `true`, additionally fetches related `ScenarioAction`
* `includeMessages`: When `true`, additionally fetches related `Message` (without `MessageHeader`)
* `includeMessageHeaders`: When `true`, additionally fetches related `Message` and `MessageHeaders`
* `includeParameters`: When `true`, additionally fetches related `ScenarioParameter`

They are all being set to `false` by default.

[[scenario-resource]]
=== Scenario Resource

The `Scenario` resource is an exception to the standard pattern.
The `GET /` endpoint returns a list of scenarios with their unique names and types, indicating whether it's a `SimulatorScenario` (`MESSAGE_TRIGGERED`) or a `ScenarioStarter` (`STARTER`).
This resource supports pagination, sorting and simple filtering.

Use the optional query parameter `nameContains` to filter scenarios by name containing the given value - case-sensitive!

This resource does not have a single resource endpoint, as scenarios are identified by name, which provides sufficient detail.
However, you can view a scenario's parameters with the `GET /{scenarioName}/parameters` endpoint or launch scenarios with the `POST /{scenarioName}/launch` endpoint, which accepts an array of parameters in the request body.

[[rest-api-pagination]]
=== Pagination

All `GET` endpoints retrieving lists of resources support pagination.
This allows clients to request subsets of records for easier navigation and processing.

.Query Parameters
* `page`: Page index, starting at 0.
* `size`: Number of records per page.
* `sort`: Sorting criteria in the format `property,(asc|desc)`.

.Request Example
To retrieve the first page with 10 records sorted by `id` in ascending order:

----
GET http://localhost:9000/api/{resource}?page=0&size=10&sort=id,asc
----

Replace `{resource}` with the appropriate resource name, see <<rest-api,REST API>>.

.Paginated Response Structure
Responses include pagination metadata in the HTTP `Link` header, in addition to the response body.
For example:

* First page: `<http://localhost:9000/api/{resource}?page=0&size=10&sort=id,asc>; rel="first"`
* Last page: `<http://localhost:9000/api/{resource}?page=9&size=10&sort=id,asc>; rel="last"`

[[rest-api-filtering]]
=== Filtering

All `GET` endpoints retrieving lists of resources support attribute-based filtering.
This allows for refined searches based on the attributes of the REST resource.

Let's consider a simplified version of the link:https://github.com/citrusframework/citrus-simulator/blob/main/simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java[`ScenarioExecution` entity] as an example:

[source,java]
----
@Entity
public class ScenarioExecution implements Serializable {

    private Long executionId;
    private Integer status = Status.UNKNOWN.getId();
    private final Set<ScenarioAction> scenarioActions = new HashSet<>();
}
----

To filter all successful executions, you can use the following query parameter: `?status=2`.
To retrieve a single execution by its ID: `?executionId=1234`.

Filtering across relationships is also possible.
For instance, to find all executions associated with a specific action, the query parameter would be: `?scenarioActionsId.in=1234`.

For more advanced filtering options, please refer to the link:https://github.com/citrusframework/citrus-simulator/tree/main/simulator-starter/src/main/java/org/citrusframework/simulator/service/criteria[criteria documentation].

.Range Filter
Numerical and date-related values support the following filters:

* `?fieldName=42` or `?fieldName.equals=42` for exact matches.
* `?fieldName.notEquals=42` for exclusion.
* `?fieldName.specified=true` to find records where `fieldName` is not null.
* `?fieldName.in=43,42` for inclusion in a list.
* `?fieldName.notIn=43,42` for exclusion from a list.
* `?fieldName.greaterThan=41` for values greater than the specified number.
* `?fieldName.lessThan=44` for values less than the specified number.
* `?fieldName.greaterThanOrEqual=42` for values greater or equal to the specified number.
* `?fieldName.lessThanOrEqual=44` for values less or equal to the specified number.

.String Filter
String attributes support the following filters:

* `?fieldName=something` or `?fieldName.equals=something` for exact matches.
* `?fieldName.notEquals=something` for exclusion.
* `?fieldName.in=something,other` for inclusion in a list.
* `?fieldName.notIn=something,other` for exclusion from a list.
* `?fieldName.contains=thing` for substring matches.
* `?fieldName.doesNotContain=thing` for exclusion of substring matches.

Remember to URL-encode query parameters to ensure proper handling of special characters and spaces.

[[rest-api-filtering-scenario-execution]]
==== Scenario Executions

The scenario execution filter has one special parameter called `headers` that accepts a very specific syntax.

* If you don't specify a key or comparator, the filter will search for messages where **any** header value **contains** the provided string. (e.g., `myValue`)
* To filter based on a **specific key**, use key=value. (e.g., `source=myApp`)
* You can also use the **CONTAINS** operator (`~`) to search within a key's value. (e.g., `name~something-like-this`)
* For numeric keys, you can use comparison operators like `<`, `\<=`, `>`, `>=`. (e.g., `priority>3`)

**Combining multiple patterns:** Separate multiple filter expressions with a semicolon (;).
They will be combined using logical **AND** operators.
(e.g., `source=myApp; status=active`)
