[[rest]]
= REST Support

The Citrus simulator can serve as an Http REST API server, handling client requests using HTTP methods such as GET, POST, PUT, DELETE, etc.

Enable generic REST support by setting the property `citrus.simulator.rest.enabled=true` in the `application.properties` file or via system property or environment variable.

[source,java]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Simulator {
    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

Setting `citrus.simulator.rest.enabled` triggers autoconfiguration steps and loads the required beans into the Spring application context.

[[rest-config]]
== Configuration

With REST support enabled, various configuration options are available, typically via a `SimulatorRestAdapter` implementation:

[source,java]
----
public abstract class SimulatorRestAdapter implements SimulatorRestConfigurer {

    @Override
    public ScenarioMapper scenarioMapper() {
        return new HttpRequestAnnotationScenarioMapper();
    }

    @Override
    public HandlerInterceptor[] interceptors() {
        return new HandlerInterceptor[] { new LoggingHandlerInterceptor() };
    }

    @Override
    public List<String> urlMappings() {
        return singletonList("/services/rest/**");
    }
}
----

The adapter allows customization of REST handling, such as implementing different scenario mappers or adding handler interceptors.

*Note*: By default, the REST support uses the `HttpRequestAnnotationScenarioMapper` to search for `@RequestMapping` annotations on scenario classes.

The `urlMappings` method defines the access path to the simulator's REST API.
Assuming the Spring Boot application runs on port 8080, the API would be accessible at:

[source]
----
http://localhost:8080/services/rest/*
----

Clients can send requests like GET, POST, DELETE to this endpoint, and the simulator will respond based on the executed scenario.

Customize the simulator REST support by extending `SimulatorRestAdapter` in a custom class:

[source,java]
----
@Component
public class MySimulatorRestAdapter extends SimulatorRestAdapter {

    @Override
    public List<String> urlMappings() {
        return singletonList("/my-rest-service/**");
    }
}
----

Annotate your custom class with `@Component` to override the default REST adapter behavior.
Now, the REST API will be accessible at `http://localhost:8080/my-rest-service/*`.

Extend the adapter directly in the main application class for further customizations:

[source,java]
----
import org.citrusframework.simulator.http.SimulatorRestAdapter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Simulator extends SimulatorRestAdapter {

    @Override
    public List<String> urlMappings() {
        return singletonList("/my-rest-service/**");
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        HeaderValueScenarioMapper scenarioMapper = new HeaderValueScenarioMapper();
        scenarioMapper.setHeaderName("X-simulator-scenario");
        return scenarioMapper;
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

[[rest-customization]]
== Advanced Customizations

For more advanced configurations, extend `SimulatorRestSupport`:

[source,java]
----
import org.citrusframework.simulator.http.SimulatorRestAutoConfiguration;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Simulator extends SimulatorRestAutoConfiguration {

    @Override
    protected String getUrlMapping() {
        return "/my-rest-service/**";
    }

    @Override
    public FilterRegistrationBean requestCachingFilter() {
        FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean(new RequestCachingServletFilter());

        String urlMapping = getUrlMapping();
        if (urlMapping.endsWith("**")) {
            urlMapping = urlMapping.substring(0, urlMapping.length() - 1);
        }
        filterRegistrationBean.setUrlPatterns(Collections.singleton(urlMapping));
        return filterRegistrationBean;
    }

    @Override
    public HandlerMapping handlerMapping(ApplicationContext applicationContext) {
        SimpleUrlHandlerMapping handlerMapping = new SimpleUrlHandlerMapping();
        handlerMapping.setOrder(Ordered.HIGHEST_PRECEDENCE);
        handlerMapping.setAlwaysUseFullPath(true);

        Map<String, Object> mappings = new HashMap<>();
        mappings.put(getUrlMapping(), getRestController(applicationContext));

        handlerMapping.setUrlMap(mappings);
        handlerMapping.setInterceptors(interceptors());

        return handlerMapping;
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

This approach allows you to override auto-configuration features like `requestCachingFilter` or `handlerMapping`.

[[rest-request-mapping]]
== Request Mapping

By default, the simulator maps incoming requests to scenarios using mapping keys evaluated from the requests.
When utilizing REST support, `@RequestMapping` annotations on scenarios can also be used:

[source,java]
----
@Scenario("Hello")
@RequestMapping(value = "/services/rest/simulator/hello", method = RequestMethod.POST, params = {"user"})
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioRunner scenario) {
        scenario.$(scenario.http()
                .receive()
                .post()
                .message()
                .body("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Say Hello!" +
                     "</Hello>"));

        scenario.$(scenario.http()
                .send()
                .response(HttpStatus.OK)
                .message()
                .body("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Hi there!" +
                     "</HelloResponse>"));
    }
}
----

In the above example, any POST request to `/services/rest/simulator/hello` with the `user` query parameter will be mapped to the `HelloScenario`.

[[rest-status-code]]
== HTTP Responses

HTTP responses in REST APIs should include appropriate status codes.
This can be easily specified using Citrus's Java DSL:

[source,java]
----
@Scenario("Hello")
@RequestMapping(value = "/services/rest/simulator/hello", method = RequestMethod.POST)
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioRunner scenario) {
        scenario.$(scenario.http()
                .receive()
                .post()
                .message()
                .body("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Say Hello!" +
                    "</Hello>"));

        scenario.$(scenario.http()
                .send()
                .response(HttpStatus.OK)
                .message()
                .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Hi there!" +
                    "</HelloResponse>"));
    }
}
----

Citrus's HTTP Java DSL simplifies setting request methods, query parameters, and status codes.
Refer to the Citrus documentation for more details on using this API.

[[rest-swagger]]
== Swagger Support

The simulator is equipped to interpret Swagger (OpenAPI V3.0) specifications, using them to automatically generate scenarios for each defined operation.
This feature streamlines the process of creating a simulator that mirrors real-world API behavior based on the Swagger documentation.

To utilize this feature, the Swagger API file should be configured within the simulator's settings.
Below is an example of how to set up Swagger support:

[source,java]
----
@SpringBootApplication
public class Simulator extends SimulatorRestAdapter {

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        return new HttpRequestPathScenarioMapper();
    }

    @Override
    public List<String> urlMappings(SimulatorRestConfigurationProperties simulatorRestConfiguration) {
        return singletonList("/petstore/v2/**");
    }

    @Override
    public EndpointAdapter fallbackEndpointAdapter() {
        return new StaticEndpointAdapter() {
            @Override
            protected Message handleMessageInternal(Message message) {
                return new HttpMessage().status(HttpStatus.NOT_FOUND);
            }
        };
    }

    @Bean
    public static HttpScenarioGenerator scenarioGenerator() {
        HttpScenarioGenerator generator = new HttpScenarioGenerator(new ClassPathResource("swagger/petstore-api.json"));
        generator.setContextPath("/petstore");
        return generator;
    }
}
----

In the above configuration, the `HttpScenarioGenerator` bean is defined with the location of the Swagger API file (`swagger/petstore-api.json`) and the context path for the API.
The `HttpRequestPathScenarioMapper` is set to handle the REST scenarios generated from the Swagger specification.

Additionally, a custom fallback endpoint adapter is defined for handling unmatched requests or validation errors.

Upon startup, the simulator dynamically generates scenarios for each operation in the Swagger API file.
These scenarios are available for review in the simulator's user interface.

Consider the following sample operation from the Swagger API file:

[source,json]
----
"/pet/findByStatus": {
  "get": {
    "tags": [
      "pet"
    ],
    "summary": "Finds Pets by status",
    "description": "Multiple status values can be provided with comma separated strings",
    "operationId": "findPetsByStatus",
    "produces": [
      "application/xml",
      "application/json"
    ],
    "parameters": [
      {
        "name": "status",
        "in": "query",
        "description": "Status values that need to be considered for filter",
        "required": true,
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "available",
            "pending",
            "sold"
          ],
          "default": "available"
        },
        "collectionFormat": "multi"
      }
    ],
    "responses": {
      "200": {
        "description": "successful operation",
        "schema": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Pet"
          }
        }
      },
      "400": {
        "description": "Invalid status value"
      }
    },
    "security": [
      {
        "petstore_auth": [
          "write:pets",
          "read:pets"
        ]
      }
    ]
  }
----

This operation would prompt the simulator to generate scenarios that validate requests against the defined criteria and provide appropriate responses, including handling different HTTP methods and query parameters.

*Important*: The current implementation primarily focuses on generating scenarios for successful cases, like `200 OK` responses.
Other variations, such as error responses, are not automatically generated but can be manually added.

.Request and Response Examples
The simulator's response to requests is based on the generated scenarios.
For a valid request, it would provide a response as defined in the Swagger specification.
Conversely, for an invalid request (e.g., missing required parameters), the simulator would respond with an error, such as `404 NOT_FOUND`.

.Additional Configuration Options
Swagger support can also be configured using system properties or environment variables, providing an alternative to programmatically setting up the `HttpScenarioGenerator`.

[source, properties]
----
# Example system properties for enabling Swagger support
citrus.simulator.rest.swagger.enabled=true
citrus.simulator.rest.swagger.api=classpath:swagger/petstore-api.json
citrus.simulator.rest.swagger.contextPath=/petstore
----

Of course, the same can be achieved using environment variables.

[source, properties]
----
CITRUS_SIMULATOR_REST_SWAGGER_ENABLED=true
CITRUS_SIMULATOR_REST_SWAGGER_API=classpath:swagger/petstore-api.json
CITRUS_SIMULATOR_REST_SWAGGER_CONTEXT_PATH=/petstore
----

.Data Dictionary Integration
To further enhance dynamic message handling, data dictionaries can be used.
These dictionaries allow for centralized manipulation of message content via JsonPath expressions, making the interaction with the simulator more dynamic and adaptable.

.Defining Data Dictionaries
Data dictionaries are defined in property files, with mappings that dictate how message content should be manipulated:

.inbound mappings
[source, properties]
----
# Example inbound data dictionary mappings
$.category.name=@assertThat(anyOf(is(dog),is(cat)))@
$.status=@matches(available|pending|sold|placed)@
$.quantity=@greaterThan(0)@
----

.outbound mappings
[source, properties]
----
# Example outbound data dictionary mappings
$.category.name=citrus:randomEnumValue('dog', 'cat')
$.name=citrus:randomEnumValue('hasso', 'cutie', 'fluffy')
----

These mappings apply to both incoming and outgoing messages, ensuring that the simulator's responses are dynamic and contextually relevant, adhering to the constraints and possibilities defined in the Swagger specification.
