[[scenario-mapper]]
== Scenario Mapper

The scenario mapper implementation determines the association between incoming request messages and simulator scenarios.
For each incoming request, a predefined scenario is triggered, which in turn generates the response message for the client.
The scenario is selected based on a mapping key, which is extracted from the incoming request.

The simulator utilizes several methods to ascertain the correct scenario from incoming request messages:

.Scenario mapping identifiers
[horizontal]
Message-Type:: Differentiates scenarios based on the request message type (XML root QName).
Content based Xpath:: Applies Xpath expressions to the request payload, using the result as the scenario identifier.
Content based JsonPath:: Applies JsonPath expressions to the request payload, using the result as the scenario identifier.
Header value:: Determines the scenario based on a specific header value in the request.
SOAP action:: Selects the scenario according to the SOAP action header in the request.
REST request mappings:: Chooses the scenario based on the HTTP method and resource path.
Request mapping annotations:: Employs Spring `@RequestMapping` annotations to map requests to scenarios based on method and path values.

When a scenario is identified using a specific mapping key, it is subsequently loaded and executed.
Each scenario performs test logic, as defined by Citrus, to provide a suitable response message.
Through this mechanism, the simulator can generate complex and dynamic responses.

The following classes implement the various scenario mapping strategies:

.Scenario mapper implementations
[horizontal]
`HttpRequestAnnotationScenarioMapper`:: Assesses REST request mappings.
`SoapActionScenarioMapper`:: Analyzes the SOAP action header.
`HeaderValueScenarioMapper`:: Evaluates message headers.
`ContentBasedXPathScenarioMapper`:: Applies an XPath expression to the message payload.
`ContentBasedJsonPathScenarioMapper`:: Applies a JsonPath expression to the message payload.

Custom scenario mapper implementations are also possible.
To introduce a custom mapper, one simply implements the interface methods of the corresponding API and incorporates the custom class into the simulator configuration, as will be detailed later in this documentation.

[[scenario-mapper-default]]
=== Default Mapping Behavior

By default, the mapping key is derived from the type of message in incoming requests, via an XPath expression targeting the root element of the message.
This unique element dictates the simulator scenario to be invoked.

For example, consider three message types: *successMessage*, *warningMessage*, and *errorMessage*.
A corresponding simulator scenario is crafted for each message type, named accordingly.
Incoming requests such as those below will prompt the simulator to select and execute the appropriate scenario:

[source,xml]
----
<successMessage>
    <text>This is a success message</text>
</successMessage>

<warningMessage>
    <text>This is a warning message</text>
</warningMessage>

<errorMessage>
    <text>This is an error message</text>
</errorMessage>
----

The root element name of each request is evaluated by the simulator to map to the respective scenario.
Each scenario yields a distinct logic for response generation, enabling tailored responses to different message types like *successMessage* as opposed to *errorMessage*.

[[scenario-mapper-configuration]]
=== Custom Mapper Configuration

The default scenario mapper can be replaced with a custom configuration in your simulator:

[source,java]
----
@Component
public class SimulatorAdapter extends SimulatorRestAdapter {
    @Override
    public ScenarioMapper scenarioMapper() {
        HeaderValueScenarioMapper scenarioMapper = new HeaderValueScenarioMapper();
        scenarioMapper.setHeaderName("X-simulator-scenario");
        return scenarioMapper;
    }
}
----

In the configuration example above, the `HeaderValueScenarioMapper` is utilized, which assesses the value of the header `X-simulator-scenario` for each incoming request message.
The scenario executed corresponds to the value of this header.
As a bean in the Spring application context, the scenario mapper comes with a default implementation, but it can be overridden in the simulator adapter configuration.
For further details on adding simulator adapter configuration classes, see the configuration chapters <<rest-config,REST configuration>>, <<web-service-config,WS configuration>>, <<jms-config,JMS configuration>> and <<endpoint-config,endpoint configuration>>.
