[[scenarios]]
== Simulator Scenarios

Simulator scenarios are defined to generate responses for incoming requests, with each scenario corresponding to distinct logic and messages.
A scenario first assigns a name for identification by mapping strategies.
It is represented by a Java class implementing the `SimulatorScenario` interface.

[source,java]
----
package org.citrusframework.simulator.scenario;

public interface SimulatorScenario {

    ScenarioEndpoint getScenarioEndpoint();

    default void run(ScenarioRunner runner) {}
}

----

Scenarios grant access to the invoked endpoint and allow message transactions through it.
Default run methods determine the logic execution pathway, depending on the desired Java DSL API.
Inheriting from `org.citrusframework.simulator.scenario.AbstractSimulatorScenario` is typical for simplifying scenario creation.

Consider the example below for a standard scenario.

[source,java]
----
@Scenario("Hello")
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioRunner scenario) {
        scenario
            .receive()
            .payload("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Say Hello!" +
                     "</Hello>");

        scenario
            .send()
            .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Hi there!" +
                     "</HelloResponse>");
    }
}
----

By extending `AbstractSimulatorScenario`, we insert receive and send logic into the run method.
The `@Scenario` annotation defines the scenario name.
Citrus Java DSL methods facilitate message handling in the implementation.

Dynamic value extraction from requests for use in responses is also supported:

[source,java]
----
@Scenario("Hello")
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioRunner scenario) {
        scenario
            .receive()
            .payload("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "<user>@ignore@</user>" +
                     "</Hello>")
            .extractFromPayload("/Hello/user", "userName");

        scenario
            .send()
            .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "<text>Hi there ${userName}!</text>" +
                     "</HelloResponse>");
    }
}
----

The `${userName}` variable is derived from the request and used to personalize the response.
This approach leverages Citrus's capability to create dynamic responses.
Both XML, JSON, and Plaintext payload types are supported by this dynamic mechanism.

Writing various scenarios enables the generation of diverse responses, with unique scenario names linked to values determined by the scenario mapper.
This setup allows for the creation of scenarios specific to incoming request messages.
Additionally, Citrus's send and receive operations handle messages across different transport types.

For more information on message transport support, see the chapters <<rest-config,REST configuration>>, <<web-service-config,WS configuration>>, <<jms-config,JMS configuration>> and <<endpoint-config,endpoint configuration>>.
