[[scenario-mapper]]
== Scenario mapper

The scenario mapper implementation decides how to map incoming request message to simulator scenarios. Each incoming request
triggers a predefined scenario that generates the response message for the calling client. The simulator identifies the scenario based
on a mapping key that is extracted from the incoming request.

There are multiple ways to identify the simulator scenario from incoming request messages:

.Scenario mapping identifiers
[horizontal]
Message-Type:: Each request message type (XML root QName) results in a separate simulator scenario
Content based Xpath:: Evaluates Xpath expressions on the request payload and uses the expression result as scenario name
Content based JsonPath:: Evaluates JsonPath expressions on the request payload and uses the expression result as scenario name
Header value:: Evaluates header name on request and uses header value as scenario name
SOAP action:: Evaluates SOAP action header on request and uses the value as scenario name
REST request mappings:: Identifies the scenario based on Http method and resource path on server
Request mapping annotations:: Uses Spring @RequestMapping annotations on scenarios in order to map incoming requests based on request method and/or request path values

Once the simulator scenario is identified with the respective mapping key the scenario get loaded and executed. All scenarios perform Citrus test logic in order
to provide a proper response messages as a result. This way the simulator is able to perform complex response generating logic with dynamic values and so on. 

The mentioned mapping key extraction strategies are implemented in these classes:

.Scenario mapper implementations
[horizontal]
HttpRequestAnnotationScenarioMapper:: Evaluates REST request mappings
SoapActionScenarioMapper:: Evaluates the SOAP action header
HeaderValueScenarioMapper:: Evaluates any message header
ContentBasedXPathScenarioMapper:: Evaluates a XPath expression on the message payload
ContentBasedJsonPathScenarioMapper:: Evaluates a JsonPath expression on the message payload

Of course you can also implement a custom scenario mapper, too. Just implement the interface methods of that API and add the implementation to the simulator
configuration as described later on in this document.

[[scenario-mapper-default]]
=== Default mapping behavior

The default mapping key logic extracts the message type of incoming requests. This is done by evaluating a Xpath expression on the request payload that uses the root element of the message as the
mapping key. Each message type gets its own simulator scenario.

Let's demonstrate that in a simple example. We know three different message types named *successMessage*, *warningMessage* and *errorMessage*. We create a simulator scenario for each of these message types with
respective naming. Given the following incoming requests the simulator will pick the matching scenario for execution. 

[source,xml]
----
<successMessage>
    <text>This is a success message</text>
</successMessage>

<warningMessage>
    <text>This is a warning message</text>
</warningMessage>

<errorMessage>
    <text>This is a error message</text>
</errorMessage>
----

The simulator evaluates the root element name and maps the requests to the matching scenario. Each scenario implements different response generating logic so the simulator is able to respond to a *successMessage* in a different
way than for *errorMessage* types.

[[scenario-mapper-configuration]]
=== Custom mapper configuration

You can change the scenario mapping behavior by overwriting the default scenario mapper in your simulator.

[source,java]
----
@Component
public class SimulatorAdapter extends SimulatorRestAdapter {
    @Override
    public ScenarioMapper scenarioMapper() {
        HeaderValueScenarioMapper scenarioMapper = new HeaderValueScenarioMapper();
        scenarioMapper.setHeaderName("X-simulator-scenario");
        return scenarioMapper;
    } 
}
----

With the configuration above we use the _HeaderValueScenarioMapper_ implementation so the header name *X-simulator-scenario* gets evaluated for each incoming request message.
Depending on that header value the matching scenario is executed as a result. The scenario mapper is just a bean in the Spring application context. There is a default implementation but you can overwrite
this behavior very easy in the simulator adapter configuration. Read more about how to add simulator adapter configuration classes in configuration chapters link:#rest-config[rest-config], link:#ws-config[ws-config]
or link:#jms-config[jms-config].
