@startuml

title __JMS Async Simulator__

participant "Application" as Application
participant "Simulator" as Simulator  <<XML>> <<JMS>>

note over Application, Simulator
Scenario: FaxQueued (default)
end note

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

|||

note over Application, Simulator
Scenario: FaxSent
end note

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: SUCCESS

|||

note over Application, Simulator
Scenario: FaxCancelled
end note

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

|||

Application ->> Simulator : cancelFax

|||

Simulator ->> Application : statusUpdate
note right: CANCELLED

|||

note over Application, Simulator
Scenario: FaxBusy
end note

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: ERROR (busy)

|||

note over Application, Simulator
Scenario: FaxNoAnswer
end note

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: ERROR (no answer)

|||

note over Application, Simulator
Scenario: FaxSendStatus (Starter)
end note

Simulator ->> Application : statusUpdate
note right: <status>

@enduml