@startuml

title __JMS Async Simulator__

participant "Application" as Application
participant "Simulator" as Simulator  <<XML>> <<JMS>>

== Scenario: FaxQueued (default) ==

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

|||

== Scenario: FaxSent ==

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: SUCCESS

|||

== Scenario: FaxCancelled ==

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

|||

Application ->> Simulator : cancelFax

|||

Simulator ->> Application : statusUpdate
note right: CANCELLED

|||

== Scenario: FaxBusy ==

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: ERROR (busy)

|||

== Scenario: FaxNoAnswer ==

Application ->> Simulator : sendFax

|||

Simulator ->> Application : statusUpdate
note right: QUEUED

... sleep 2 seconds ...

Simulator ->> Application : statusUpdate
note right: ERROR (no answer)

|||

== Scenario: FaxSendStatus (Starter) ==

Simulator ->> Application : statusUpdate
note right: <status>

@enduml