[[concepts]]
= Concepts

The Citrus simulator project has the primary focus to provide messaging simulation as a standalone server. Once started the simulator
provides different endpoints (Http REST, JMS, SOAP Web Service, and so on) and waits for incoming requests. The time a request arrives at one of the endpoints
the simulator maps the request to a predefined link:#scenarios[simulator scenario] which is automatically executed immediately. The scenario is responsible to create
a response message that is sent to the calling client.

The scenario mapping is done by link:#scenario-mapper[extracting a mapping key] from the request data. This scenario mapper implementation searches for a matching scenario for the current incoming
request. The scenario mapping is done based on different identifiers on the request. The Citrus simulator knows following scenario mapper implementations:

.Scenario mapper
[horizontal]
Content based xpath mapper:: Evaluates Xpath expressions on the request payload and uses the expression result as scenario name
Content based jsonPath mapper:: Evaluates JsonPath expressions on the request payload and uses the expression result as scenario name
Header value mapper:: Evaluates header name on request and uses header value as scenario name
SOAP action mapper:: Evaluates SOAP action header on request and uses the value as scenario name
Request mapping annotation mapper:: Uses Spring @RequestMapping annotations on scenarios in order to map incoming requests based on request method and/or request path values

The link:#scenarios[simulator scenario] is capable of handling the request message and will return a proper response message to the calling client.
With different scenarios defined the simulator is able to respond to different requests accordingly.

Each scenario defines a very special simulation logic by using Citrus test actions that perform once the scenario is triggered by incoming requests.

This way each incoming request is processed and a proper response message is provided to the client. You can define default and fallback scenarios for
each simulator.

In addition to that the simulator provides a link:#user-interface[user interface] where executed scenarios state success or failure.
Also you can trigger scenarios manually.

[[concept-simulator-application]]
== Simulator application

The simulator is based on Spring boot. This means we have a main class that loads the Spring boot application.

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableRest;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableRest
public class Simulator {
    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

This class is the main entrance for all configuration and customization statements. First of all the class is annotated as *@SpringBootApplication*
and *@SimulatorApplication*. This enables auto configuration for the simulator application. In addition to that we enable different aspects of the simulator
by using further annotations provided. In the sample above we use the *@EnableRest* annotation for Http REST endpoint support.

There are multiple annotations available for different transport endpoints:

.Simulator annotations
[horizontal]
@EnableRest:: Enables link:#rest-support[Http REST support]
@EnableWebService:: Enables link:#ws-support[SOAP web services support]
@EnableWebServiceClient:: Enables link:#ws-support[SOAP web services support]
@EnableJms:: Enables link:#jms-support[JMS support]
@EnableEndpointComponent:: Enables generic link:#endpoint-component-support[endpoint component support]

[[concept-simulator-properties]]
== Simulator properties

The simulator is capable of loading configuration from system properties, environment variables and property files. First of all the default Spring boot properties configuration mechanism
is supported. Following from that you can add properties to the `application.properties` file in your project resources in order to adjust simulator behavior.

[source,properties]
----
citrus.simulator.defaultTimeout=10000
citrus.simulator.templatePath=com/company/simulator/templates
----

The available simulator properties are grouped in following configuration classes:

[horizontal]
com.consol.citrus.simulator.config.SimulatorConfigurationProperties:: prefix=*citrus.simulator*
com.consol.citrus.simulator.annotation.SimulatorRestConfigurationProperties:: prefix=*citrus.simulator.rest*
com.consol.citrus.simulator.annotation.SimulatorWebServiceConfigurationProperties:: prefix=*citrus.simulator.ws*
com.consol.citrus.simulator.annotation.SimulatorJmsConfigurationProperties:: prefix=*citrus.simulator.jms*

There are several properties that you can use in order to customize the simulator behavior. These
properties are:

.Spring boot application properties
[horizontal]
citrus.simulator.templatePath:: Default path to message payload template files.
citrus.simulator.defaultScenario:: Default scenario name.
citrus.simulator.defaultTimeout:: Timeout when waiting for inbound messages.
citrus.simulator.templateValidation:: Enable/disable schema validation.
citrus.simulator.exceptionDelay:: Default delay in milliseconds to wait after uncategorized exceptions.
citrus.simulator.rest.urlMapping:: Handler adapter url mapping for inbound requests
citrus.simulator.ws.servletMapping:: Message dispatcher servlet mapping for inbound SOAP requests
citrus.simulator.jms.inboundDestination:: JMS destination name to consume inbound messages from
citrus.simulator.jms.replyDestination:: JMS destination name to publish reply messages to

Please refer to the respective configuration property classes to see what property settings are supported.

[[concept-simulator-system-properties]]
=== System properties

In addition to that default Spring boot property replacement the simulator also supports system property and environment variables. The properties are:

.System property names
[horizontal]
citrus.simulator.configuration.class:: Java configuration class that is automatically loaded. (default is com.consol.citrus.simulator.SimulatorConfig)
citrus.simulator.template.path:: Default path to message payload template files.
citrus.simulator.default.scenario:: Default scenario name.
citrus.simulator.default.timeout:: Timeout when waiting for inbound messages.
citrus.simulator.template.validation:: Enable/disable schema validation.
citrus.simulator.exception.delay:: Default delay in milliseconds to wait after uncategorized exceptions.
citrus.simulator.rest.url.mapping:: Handler adapter url mapping for inbound requests
citrus.simulator.ws.servlet.mapping:: Message dispatcher servlet mapping for inbound SOAP requests
citrus.simulator.jms.inbound.destination:: JMS destination name to consume inbound messages from
citrus.simulator.jms.reply.destination:: JMS destination name to publish outbound messages to

You can set these properties as system properties when starting the Spring boot web application or you can add the properties to the default
Spring Boot application properties file *application.properties* that is located as resource file in your project.

The simulator will automatically load these properties during startup and honor this configuration.

[[concept-simulator-environment-variables]]
=== Environment variables

Same settings that are editable via system properties are also accessible via environment variables. This is extremely helpful when running the simulator in a containerized
infrastructure such as Docker or Kubernetes.

.Environment settings
[horizontal]
CITRUS_SIMULATOR_CONFIGURATION_CLASS:: Java configuration class that is automatically loaded. (default is com.consol.citrus.simulator.SimulatorConfig)
CITRUS_SIMULATOR_TEMPLATE_PATH:: Default path to message payload template files.
CITRUS_SIMULATOR_DEFAULT_SCENARIO:: Default scenario name.
CITRUS_SIMULATOR_DEFAULT_TIMEOUT:: Timeout when waiting for inbound messages.
CITRUS_SIMULATOR_TEMPLATE_VALIDATION:: Enable/disable schema validation.
CITRUS_SIMULATOR_EXCEPTION_DELAY:: Default delay in milliseconds to wait after uncategorized exceptions.
CITRUS_SIMULATOR_REST_URL_MAPPING:: Handler adapter url mapping for inbound requests
CITRUS_SIMULATOR_WS_SERVLET_MAPPING:: Message dispatcher servlet mapping for inbound SOAP requests
CITRUS_SIMULATOR_JMS_INBOUND_DESTINATION:: JMS destination name to consume inbound messages from
CITRUS_SIMULATOR_JMS_REPLY_DESTINATION:: JMS destination name to publish outbound messages to

In case these environment variables are present on your local system the simulator will automatically load these settings during startup and honor the configuration.

[[concept-simulator-spring-configuration]]
== Spring bean configuration

Citrus works with the Spring framework and the simulator is a Spring boot application. Therefore the configuration is done by adding and overwriting Spring beans in
the application context. The simulator automatically loads Spring beans defined in following locations:

* *META-INF/citrus-simulator.xml* Xml Spring bean configuration file.
* *com.consol.citrus.simulator.SimulatorConfig* Java configuration class. You can customize this class by defining the property *citrus.simulator.configuration.class*

All beans defined in there get automatically loaded to the simulator Spring application context.

include::scenario-mapper.adoc[]
include::scenarios.adoc[]
include::intermediate-messages.adoc[]
