[[endpoint-support]]
= Endpoint support

We have seen how the simulator handles different transports such as link:#rest-support[Http REST], link:#ws-support[SOAP web services] and link:#jms-support[JMS].
Now the simulator is also able to handle other message transports such as mail communication, JMX mbean server, RMI invocations and much more. The
simulator is able to deal with any kind of endpoint component that is supported in Citrus framework.

The generic endpoint support is added with *@EnableEndpointComponent* annotation.

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableEndpointComponent;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableEndpointComponent
public class Simulator {
    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

The *@EnableEndpointComponent* annotation performs some auto configuration steps and loads required beans for the Spring application context
in the Spring boot application. Once we use that feature we can have any Citrus endpoint component as inbound source for simulator scenarios. This means
we can have a mail server or a RMI server that is simulated with proper response messages.

As we are using generic endpoint components as inbound source we need to set the endpoint in the configuration. Read about that in the following sections.

[[endpoint-config]]
== Configuration

When using generic Citrus endpoints as simulator inbound source we need to configure those endpoint components. The most comfortable way is to
add a *SimulatorEndpointComponentAdapter* implementation to the classpath. The adapter provides several configuration methods.

[source,java]
----
public abstract class SimulatorEndpointComponentAdapter implements SimulatorEndpointComponentConfigurer {

    @Override
    public abstract Endpoint endpoint(ApplicationContext applicationContext);

    @Override
    public boolean useSoapEnvelope() {
        return false;
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        return new ContentBasedXPathScenarioMapper().addXPathExpression("local-name(/*)");
    }
}
----

The adapter defines methods that configure the endpoint component used as inbound source. As usual we can set the mapping key extractor implementation or
add automatic SOAP envelope support.

More importantly we need to define an inbound endpoint that is used as source for scenarios. Let's have a simple endpoint component adapter example.

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableEndpointComponent;
import com.consol.citrus.simulator.annotation.SimulatorEndpointComponentAdapter;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableEndpointComponent
public class Simulator extends SimulatorEndpointComponentAdapter {

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }

    @Override
    public Endpoint endpoint(ApplicationContext applicationContext) {
        MailServer mailServer = new MailServer();
        mailServer.setPort(2222);
        mailServer.setAutoStart(true);

        return mailServer;
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        return new ContentBasedXPathScenarioMapper()
                        .addNamespaceMapping("mail", "http://www.citrusframework.org/schema/mail/message")
                        .addXPathExpression("/mail:mail-message/mail:subject");
    }
}
----

The custom adapter defines a Citrus mail server endpoint that should be used as inbound source. Any mail message that arrives at this mail server component will
trigger a new simulator scenario then. Also we overwrite the mapping key extractor implementation so that the mail subject evaluates to the scenario that should be executed.

This configuration would lead us to a mail server that responds to incoming mail messages base on the mail subject. So we can have several simulator
scenarios for different mail messages.

[source,java]
----
@Scenario("Hello")
public class HelloScenario extends SimulatorEndpointScenario {

    @Override
    public void run(ScenarioDesigner scenario) {
        scenario
            .receive()
            .payload("<mail-message xmlns=\"http://www.citrusframework.org/schema/mail/message\">" +
                        "<from>user@citrusframework.org</from>" +
                        "<to>citrus@citrusframework.org</to>" +
                        "<cc></cc>" +
                        "<bcc></bcc>" +
                        "<subject>Hello</subject>" +
                        "<body>" +
                            "<contentType>text/plain; charset=utf-8</contentType>" +
                            "<content>Say Hello!</content>" +
                        "</body>" +
                    "</mail-message>");

        scenario
            .send()
            .payload("<mail-response xmlns=\"http://www.citrusframework.org/schema/mail/message\">" +
                        "<code>250</code>" +
                        "<message>OK</message>" +
                    "</mail-response>");
    }
}
----

The scenario implementation above uses the base class *SimulatorEndpointScenario* and listens for mail messages of subject *Hello*. The
mail XML marshalling is automatically done by Citrus. This is the usual way how the Citrus mail component handles mail messages and responses. That means we can use the default Citrus
features in our simulator, too. The scenario sends back a positive mail response to the calling client.

This is how we can use any Citrus endpoint component as simulator inbound source. This gives us the opportunity to support a huge set of message transports and
message types in our simulator applications. Each incoming request on the endpoint component triggers a new simulator scenario.