[[installation]]
= Installation

The Citrus simulator is a web application that uses Spring boot and Angular2. The simulator is able to run as Java application on your local machine
or as container/pod in Docker, Kubernetes or Openshift.

[[maven]]
== Maven

You can use the simulator in your Maven project. Maven will automatically download all required dependencies and project artifacts for you. The simulator is then executable
as a web archive representing the the latest simulator distribution.

See the following sample Maven project POM file that defines the project sources as Spring boot application.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.consol.citrus</groupId>
  <artifactId>citrus-simulator-sample</artifactId>
  <name>${project.artifactId}</name>
  <version>1.0.0</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <citrus.simulator.version>1.0.0</citrus.simulator.version>
    <spring.boot.version>1.5.6.RELEASE</spring.boot.version>
    <testng.version>6.11</testng.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>

    <!-- Citrus Simulator -->

    <dependency>
      <groupId>com.consol.citrus</groupId>
      <artifactId>citrus-simulator-starter</artifactId>
      <version>${citrus.simulator.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <encoding>${project.build.sourceEncoding}</encoding>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring.boot.version}</version>
        <configuration>
          <fork>true</fork>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
----

You can now build and run the simulator with Maven from a command line. Use following commands:

[source,bash]
----
mvn clean install

mvn spring-boot:run
----

You will see the application starting up. Usually you will see some console log output. The web server should start within seconds. Once the application is up and running
you can open your browser and point to link:http://localhost:8080[http://localhost:8080].

That's it you are ready to use the Citrus simulator now. Next thing would be to understand the link:#concepts[concepts] and create some link:#scenarios[simulator scenarios].

[[maven-archetype]]
== Maven archetype

The easiest way to get started with a new simulator project is to use a Maven archetype that creates a new project for you.

[source,bash]
----
mvn archetype:generate -B -DarchetypeGroupId=com.consol.citrus.archetypes \
                            -DarchetypeArtifactId=citrus-simulator-archetype-rest \
                            -DarchetypeVersion=${citrus.simulator.version} \
                            -DgroupId=com.consol.citrus.simulator \
                            -DartifactId=citrus-simulator-rest \
                            -Dversion=1.0.0
----

If you execute the command above the Maven archetype generator will ask you some questions about versions and project names. Once you have completed the generation
you get a new Maven project that is ready to use. The project is created in a new folder on your machine. Switch to that folder and continue to build the project.

There are different simulator archetypes available. Please pick the most convenient archetype according to your project purpose.

.Maven archetypes
[horizontal]
citrus-simulator-archetype-rest:: Http REST simulator sample
citrus-simulator-archetype-ws:: SOAP web service simulator sample
citrus-simulator-archetype-jms:: JMS simulator sample
citrus-simulator-archetype-mail:: Mail simulator sample
citrus-simulator-archetype-swagger:: Auto generate simulator from Swagger Open API specification (_experimental_)
citrus-simulator-archetype-wsdl:: Auto generate simulator from SOAP WSDL specification (_experimental_)

[[development]]
=== Development

You can directly build the new simulator project with

[source,bash]
----
mvn install
----

This compiles, tests and packages the new simulator project on your local machine. Now we can run the simulator:

[source,bash]
----
mvn spring-boot:run
----

You will see the application starting up. Usually you will see some console log output. The web server should start within seconds. Once the application is up and running
you can open your browser and point to link:http://localhost:8080[http://localhost:8080].

Now everything is set up and you can start to create some simulator scenarios. 

That's it you are ready to use the Citrus simulator.