[[introduction]]
= Introduction

This is a standalone simulator for different message transports such as Http REST, SOAP WebService,
JMS, RMI and mail messaging.

The simulator provides server APIs for clients and responds with predefined messages according to
defined scenarios. The simulator response logic is very powerful and enables us to simulate any kind of server interface.

The simulator uses link:https://projects.spring.io/spring-boot/[Spring Boot] in combination with the test framework link:https://www.citrusframework.org[Citrus]. You can
code simulator scenarios in Java or XML. Each scenario execution on the simulator is stored to an internal database and can be reviewed via web UI in the browser.

Feedback and contributions are highly appreciated!

[[limitations]]
== Limitations

*NOTE:* _This project is considered stable but still under construction!_

The simulator application is stable not yet finished. Some features are still under construction. Some aspects are simply not covered yet.

Following from that we have to deal with some limitations and trade offs until the project emerges (hopefully with the help of the community, keeping our fingers crossed!).
However the simulator is usable and most features are considered to be stable.

Please consider following limitations that we have right now:

[[limitations-java-8]]
=== Java 8

The simulator is a Java application coded in Java 8. Following from that you need at least Java 8 to run it as a Spring Boot web application.
Please make sure that you have Java development kit installed and set up. You can verify this with this command in a new terminal window.

[source,bash]
----
java -version
----

[[limitations-browser]]
=== Browser

The simulator provides a small web user interface when started. You can access this web UI with your browser. As we are in an early state in this project we do not
invest much time in full cross-browser compatibility. We use Chrome and Firefox during development. So the simulator application is most likely to be 100% working
on these two browsers. Of course other browsers might work without any limitations, too.