[[rest]]
= REST support

The simulator is able to provide Http REST APIs as a server. Clients can call the simulator on request paths using methods such as
Http GET, POST, PUT, DELETE and so on. The simulator defines a special REST enabling annotation that we can use on the application class:

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableRestSimulation;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableRestSimulation
public class Simulator {
    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

The *@EnableRestSimulation* annotation performs some auto configuration steps and loads required beans for the Spring application context
in the Spring boot application.

After that we are ready to handle incoming REST API calls on the simulator.

[[rest-config]]
== Configuration

Once the REST support is enabled on the simulator we have different configuration options. The most comfortable way is to
add a *SimulatorRestAdapter* implementation to the classpath. The adapter provides several configuration methods.

[source,java]
----
public abstract class SimulatorRestAdapter implements SimulatorRestConfigurer {

    @Override
    public ScenarioMapper scenarioMapper() {
        return new HttpRequestAnnotationScenarioMapper();
    }

    @Override
    public HandlerInterceptor[] interceptors() {
        return new HandlerInterceptor[] { new LoggingHandlerInterceptor() };
    }

    @Override
    public String urlMapping() {
        return "/services/rest/**";
    }
}
----

The adapter defines methods that configure the simulator REST handling. For instance we can add another scenario mapper implementation or
add handler interceptors to the REST API call handling.

*Note*
The REST support is using the default scenario mapper *HttpRequestAnnotationScenarioMapper* that searches for *@RequestMapping* annotations
on scenario classes. Read more about that in link:#rest-request-mapping[rest-request-mapping].

The *urlMapping* defines how clients can access the simulator REST API. Assuming the Spring boot simulator application is running on port 8080 the
REST API would be accessible on this URI:

[source]
----
http://localhhost:8080/services/rest/*
----

The clients can send GET, POST, DELETE and other calls to that endpoint URI then. The simulator will respond with respective responses based on the called
scenario.

You can simply extend the adapter in a custom class for adding customizations.

[source,java]
----
@Component
public class MySimulatorRestAdapter extends SimulatorRestAdapter {

    @Override
    public String urlMapping() {
        return "/my-rest-service/**";
    }
}
----

As you can see the class is annotated with *@Component* annotation. This is because the adapter should be recognized by Spring in order to overwrite the default
REST adapter behavior. The custom adapter just overwrites the *urlMapping* method so the REST simulator API will be accessible for clients under this endpoint URI:

[source]
----
http://localhhost:8080/my-rest-service/*
----

This is the simplest way to customize the simulator REST support. We can also use the adapter extension directly on the Spring boot main application class:

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableRestSimulation;
import com.consol.citrus.simulator.annotation.SimulatorRestAdapter;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableRestSimulation
public class Simulator extends SimulatorRestAdapter {

    @Override
    public String urlMapping() {
        return "/my-rest-service/**";
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        HeaderValueScenarioMapper scenarioMapper = new HeaderValueScenarioMapper();
        scenarioMapper.setHeaderName("X-simulator-scenario");
        return scenarioMapper;
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

So we have *@EnableRestSimulation* and REST adapter customizations combined on one single class.

[[rest-customization]]
== Advanced customizations

For a more advanced configuration option we can extend the *SimulatorRestSupport* implementation.

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableRest;
import com.consol.citrus.simulator.annotation.SimulatorRestSupport;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
public class Simulator extends SimulatorRestSupport {

    @Override
    protected String getUrlMapping() {
        return "/my-rest-service/**";
    }

    @Override
    public FilterRegistrationBean requestCachingFilter() {
        FilterRegistrationBean filterRegistrationBean = new FilterRegistrationBean(new RequestCachingServletFilter());

        String urlMapping = getUrlMapping();
        if (urlMapping.endsWith("**")) {
            urlMapping = urlMapping.substring(0, urlMapping.length() - 1);
        }
        filterRegistrationBean.setUrlPatterns(Collections.singleton(urlMapping));
        return filterRegistrationBean;
    }

    @Override
    public HandlerMapping handlerMapping(ApplicationContext applicationContext) {
        SimpleUrlHandlerMapping handlerMapping = new SimpleUrlHandlerMapping();
        handlerMapping.setOrder(Ordered.HIGHEST_PRECEDENCE);
        handlerMapping.setAlwaysUseFullPath(true);

        Map<String, Object> mappings = new HashMap<>();
        mappings.put(getUrlMapping(), getRestController(applicationContext));

        handlerMapping.setUrlMap(mappings);
        handlerMapping.setInterceptors(interceptors());

        return handlerMapping;
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

With that configuration option we can overwrite REST support auto configuration features on the simulator such as the *requestCachingFilter* or the *handlerMapping*.
We can not use the *@EnableRestSimulation* auto configuration annotation then. Instead we extend the *SimulatorRestSupport* implementation directly.

[[rest-request-mapping]]
== Request mapping

By default the simulator will map incoming requests to scenarios using so called mapping keys that are evaluated on the incoming request. When using REST support on
the simulator we can also use *@RequestMapping* annotations on scenarios in order to map incoming requests.

This looks like follows:

[source,java]
----
@Scenario("Hello")
@RequestMapping(value = "/services/rest/simulator/hello", method = RequestMethod.POST)
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioDesigner scenario) {
        scenario
            .receive()
            .payload("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Say Hello!" +
                     "</Hello>");

        scenario
            .send()
            .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Hi there!" +
                     "</HelloResponse>");
    }
}
----

As you can see the example above uses *@RequestMapping* annotation in addition to the *@Scenario* annotation. All requests on the request path
*/services/rest/simulator/hello* of method *POST* will be mapped to the scenario. With this strategy the simulator is able to map requests based
on methods, request paths and query parameters.

The mapping strategy requires a special scenario mapper implementation that is used by default. This scenario mapper automatically scans for scenarios with *@RequestMapping* annotations.
The *HttpRequestAnnotationScenarioMapper* is active by default when enabling REST support on the simulator. Of course you can use traditional scenario mappers, too when using REST.
So in case you need to apply different mapping strategies you can overwrite the scenario mapper implementation in the configuration adapter.

[[rest-status-code]]
== Http responses

As Http is a synchronous messaging transport by its nature we can provide response messages to the calling client. In Http REST APIs this should include some Http status code.
You can specify the Http status code very easy when using the Citrus Java DSL methods as shown in the next example.

[source,java]
----
@Scenario("Hello")
@RequestMapping(value = "/services/rest/simulator/hello", method = RequestMethod.POST)
public class HelloScenario extends AbstractSimulatorScenario {

    @Override
    public void run(ScenarioDesigner scenario) {
        scenario
            .http()
            .receive()
            .post()
            .payload("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                    "Say Hello!" +
                    "</Hello>");

        scenario
            .http()
            .send()
            .response(HttpStatus.OK)
            .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                    "Hi there!" +
                    "</HelloResponse>");
    }
}
----

The Http Java DSL extension in Citrus provides easy access to Http related identities such as request methods, query parameters and status codes. Please
see the official Citrus documentation for more details how to use this Http specific Java fluent API.

[[rest-swagger]]
== Swagger support

The simulator application is able to read link:https://swagger.io/[Swagger] link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md[Open API V3.0] specifications for auto
generating simulator scenarios for each operation. The Open API specification defines available REST request paths, supported methods (GET, POST, PUT, DELETE, ...) and their outcome when clients
call that API operations. The simulator generates basic scenarios for these specification information.

See the following sample how to do that:

[source,java]
----
@SpringBootApplication
@SimulatorApplication
@EnableRestSimulation
public class Simulator extends SimulatorRestAdapter {

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }

    @Override
    public ScenarioMapper scenarioMapper() {
        return new HttpRequestPathScenarioMapper();
    }

    @Override
    public String urlMapping(SimulatorRestConfigurationProperties simulatorRestConfiguration) {
        return "/petstore/v2/**";
    }

    @Override
    public EndpointAdapter fallbackEndpointAdapter() {
        return new StaticEndpointAdapter() {
            @Override
            protected Message handleMessageInternal(Message message) {
                return new HttpMessage().status(HttpStatus.NOT_FOUND);
            }
        };
    }

    @Bean
    public static HttpScenarioGenerator scenarioGenerator(SimulatorConfigurationProperties simulatorConfiguration) {
        HttpScenarioGenerator generator = new HttpScenarioGenerator(new ClassPathResource("swagger/petstore-api.json"));
        generator.setSimulatorConfiguration(simulatorConfiguration);
        generator.setContextPath("/petstore");
        return generator;
    }
}
----

The listing above add a `HttpScenarioGenerator` as Spring bean to the simulator application. The generator receives the swagger api file location `swagger/petstore-api.json` and the
context path for this API. In addition to that we need to set a special scenario mapper implementation `HttpRequestPathScenarioMapper` that is aware of generated REST scenarios.

Also we set a custom fallback endpoint adapter. This one is used when no scenario matched the incoming request or when the scenario itself did not produce a proper response because of
some validation error.

On startup the generator dynamically generates a scenario for each operation defined in that swagger api file. You can review all generated scenarios in the user interface.

Let's have a look at a sample operation in that *petstore* swagger api file:

[source,json]
----
"/pet/findByStatus": {
  "get": {
    "tags": [
      "pet"
    ],
    "summary": "Finds Pets by status",
    "description": "Multiple status values can be provided with comma separated strings",
    "operationId": "findPetsByStatus",
    "produces": [
      "application/xml",
      "application/json"
    ],
    "parameters": [
      {
        "name": "status",
        "in": "query",
        "description": "Status values that need to be considered for filter",
        "required": true,
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "available",
            "pending",
            "sold"
          ],
          "default": "available"
        },
        "collectionFormat": "multi"
      }
    ],
    "responses": {
      "200": {
        "description": "successful operation",
        "schema": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Pet"
          }
        }
      },
      "400": {
        "description": "Invalid status value"
      }
    },
    "security": [
      {
        "petstore_auth": [
          "write:pets",
          "read:pets"
        ]
      }
    ]
  }
}
----

The REST operation above defines a *GET* method on */pet/findByStatus*. The required query parameter *status* is defined to filter the returned list of pets. As a response
the API defines *200 OK* with an array of *Pet* objects. In addition to that *400* response is defined when the *status* parameter is not within its restriction enumeration *available, pending, sold*.

*IMPORTANT:* _The simulator will always generate the success case exclusively. Here this would be the *200 OK* response. Other response variations are not generated up to now!_

The generated scenario for this operation verifies that the request is using *GET* method on request path */pet/findByStatus*. Also the scenario verifies the existence of the *status* query
parameter and that the value is within the enumeration boundaries.

Only in case these verification steps are performed successfully the simulator scenario generates a proper response *200 OK* that contains a dynamic array of pet objects.

Let's have a look at the communication on that scenario:

.Request
[source]
----
GET http://localhost:8080/petstore/v2/pet/findByStatus?status=pending
Accept:application/json
Content-Type:text/plain;charset=UTF-8
Content-Length:0
----

.Response
[source]
----
HTTP/1.1 200
X-Application-Context:application
Content-Type:application/json
Content-Length:193
Date:Wed, 13 Sep 2017 08:13:52 GMT

[{"id": 5243024128,"category": {"id": 5032916791,"name": "hneBENfFDq"},"name": "JjZhcsvSRA","photoUrls": ["GwSVIBOhsi"],"tags": [{"id": 8074462757,"name": "DYwotNekKc"}],"status": "available"}]
----

The request did match all verification steps on the simulator for this operation. Following from that we receive a generated response message with some sample data as array of pet objects. The simulator
is able to generate dynamic identifier such as *id*, *category* and *name* values. According to the field type the simulator generates dynamic number of string values. When there is a enumeration value restriction as seen in *status*
the simulator generates a dynamic enumeration value.

This is how we always get a proper generated response from the simulator API. The petstore swagger Open API specification defines the returned objects and how to validate the incoming requests.

Just in case we sent an invalid request according to the Open API specification we do not get a proper response.

.Request
[source]
----
GET http://localhost:8080/petstore/v2/pet/findByStatus
Accept:application/json
Content-Type:text/plain;charset=UTF-8
Content-Length:0
----

.Response
[source]
----
HTTP/1.1 404
X-Application-Context:application
Content-Type:text/plain;charset=UTF-8
Content-Length:0
Date:Wed, 13 Sep 2017 08:42:56 GMT
----

The sample request above is missing the required *status* query parameter on the *findByStatus* operation. As a result we get a *404 NOT_FOUND* response from the fallback endpoint adapter
as the scenario did not complete because of validation errors. You will see the failed scenario activity with proper error message on that missing *status* parameter in the user interface then.

This completes the auto generated scenario functionality based on Swagger Open API specifications.