[[web-service]]
= Web Service support

The simulator is able to handle SOAP Web Service calls as a server. The simulator defines a special
SOAP enabling annotation that we can use on the application class:

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableWebService;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableWebService
public class Simulator {
    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

The *@EnableWebService* annotation performs some auto configuration steps and loads required beans for the Spring application context
in the Spring boot application.

After that we are ready to handle incoming SOAP Web Service calls on the simulator. We can use the default scenario base class for SOAP Web Services.

[source,java]
----
@Scenario("Hello")
public class HelloScenario extends SimulatorWebServiceScenario {

    @Override
    public void run(ScenarioDesigner scenario) {
        scenario
            .receive(scenario.inboundEndpoint())
            .payload("<Hello xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Say Hello!" +
                     "</Hello>")
            .header(SoapMessageHeaders.SOAP_ACTION, "Hello");

        scenario
            .send()
            .payload("<HelloResponse xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Hi there!" +
                     "</HelloResponse>");
    }
}
----

The *SimulatorWebServiceScenario* automatically handles the SOAP envelope so we do not have to deal with that in the scenario receive and send operations. Also
the scenario receive operation has access to the SOAP action of the incoming request call. Besides that we can also link:#ws-soap-faults[return a SOAP fault] message as scenario outcome.

Let's move on with having a look at the SOAP related configuration options as described in the following sections.

[[web-service-config]]
== Configuration

Once the SOAP support is enabled on the simulator we have different configuration options. The most comfortable way is to
add a *SimulatorWebServiceAdapter* implementation to the classpath. The adapter provides several configuration methods.

[source,java]
----
public abstract class SimulatorWebServiceAdapter implements SimulatorWebServiceConfigurer {
    @Override
    public String servletMapping() {
        return "/services/ws/*";
    }

    @Override
    public MappingKeyExtractor mappingKeyExtractor() {
        return new XPathPayloadMappingKeyExtractor();
    }

    @Override
    public EndpointInterceptor[] interceptors() {
        return new EndpointInterceptor[] { new LoggingEndpointInterceptor() };
    }
}
----

The adapter defines methods that configure the simulator SOAP message handling. For instance we can add another mapping key extractor implementation or
add endpoint interceptors to the SOAP service call handling.

The *servletMapping* defines how clients can access the simulator SOAP service. Assuming the Spring boot simulator application is running on port 8080 the
SOAP service would be accessible on this URI:

[source]
----
http://localhhost:8080/services/ws/*
----

The clients can send SOAP calls to that endpoint URI then. The simulator will respond with respective SOAP responses based on the called
scenario.

You can simply extend the adapter in a custom class for adding customizations.

[source,java]
----
@Component
public class MySimulatorWebServiceAdapter extends SimulatorWebServiceAdapter {

    @Override
    public String servletMapping() {
        return "/my-soap-service/**";
    }
}
----

As you can see the class is annotated with *@Component* annotation. This is because the adapter should be recognized by Spring in order to overwrite the default
SOAP adapter behavior. The custom adapter just overwrites the *servletMapping* method so the SOAP simulator API will be accessible for clients under this endpoint URI:

[source]
----
http://localhhost:8080/my-soap-service/*
----

This is the simplest way to customize the simulator SOAP support. We can also use the adapter extension directly on the Spring boot main application class:

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableWebService;
import com.consol.citrus.simulator.annotation.SimulatorWebServiceAdapter;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
@EnableWebService
public class Simulator extends SimulatorWebServiceAdapter {

    @Override
    public String servletMapping() {
        return "/my-soap-service/**";
    }

    @Override
    public MappingKeyExtractor mappingKeyExtractor() {
        return new SoapActionMappingKeyExtractor();
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

So we have *@EnableWebService* and SOAP adapter customizations combined on one single class.

[[web-service-customization]]
== Advanced customizations

For a more advanced configuration option we can extend the *SimulatorWebServiceSupport* implementation.

[source,java]
----
import com.consol.citrus.simulator.annotation.EnableWebService;
import com.consol.citrus.simulator.annotation.SimulatorWebServiceSupport;
import com.consol.citrus.simulator.annotation.SimulatorApplication;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SimulatorApplication
public class Simulator extends SimulatorWebServiceSupport {

    @Override
    protected String getServletMapping() {
        return "/my-soap-service/**";
    }

    @Bean
    public ServletRegistrationBean messageDispatcherServlet(ApplicationContext applicationContext) {
        MessageDispatcherServlet servlet = new MessageDispatcherServlet();
        servlet.setApplicationContext(applicationContext);
        servlet.setTransformWsdlLocations(true);
        return new ServletRegistrationBean(servlet, getDispatcherServletMapping());
    }

    public static void main(String[] args) {
        SpringApplication.run(Simulator.class, args);
    }
}
----

With that configuration option we can overwrite SOAP support auto configuration features on the simulator such as the *messageDispatcherServlet*.
We can not use the *@EnableWebService* auto configuration annotation then. Instead we extend the *SimulatorWebServiceSupport* implementation directly.

[[web-service-faults]]
== SOAP faults

The simulator is in charge of sending proper response messages to the calling client. When using SOAP we might also want to send
back a SOAP fault message. Therefore the default Web Service scenario implementation also provides fault responses as scenario result.

[source,java]
----
@Scenario("GoodNight")
public class GoodNightScenario extends SimulatorWebServiceScenario {

    @Override
    protected void configure() {
        scenario
            .receive()
            .payload("<GoodNight xmlns=\"http://citrusframework.org/schemas/hello\">" +
                        "Go to sleep!" +
                     "</GoodNight>")
            .header(SoapMessageHeaders.SOAP_ACTION, "GoodNight");

        scenario
            .sendFault()
            .faultCode("{http://citrusframework.org}CITRUS:SIM-1001")
            .faultString("No sleep for me!");
    }
}
----

The example above shows a simple fault generating SOAP scenario. The base class *SimulatorWebServiceScenario* provides
the *sendFault()* method in order to create proper SOAP fault messages. The simulator automatically add SOAP envelope and SOAP fault
message details for you. So we can decide wheather to provide a success response or SOAP fault.