#!/bin/bash

# Checks if git subtree has changes in given top directory
check_git_clean() {
    local dir=$1

    cd $dir
    echo "==== Checking for clean Git Repo"
    set +e
    git diff-index --quiet HEAD --
    local git_uncommitted=$?
    set -e
    if [ $git_uncommitted != 0 ]; then
       git status
       echo "Untracked or changed files exist. Please run release on a clean repo"
       exit 1
    fi
}

git_commit() {
    local dir=$1
    local pattern="$2"
    local message="${3:-}"
    echo "==== Committing files to local git"
    cd $dir
    if [ -n "$message" ]; then
        git ls-files --modified | grep $pattern | xargs git commit -m "$message"
    else
        git ls-files --modified | grep $pattern | xargs git commit --amend --no-edit
    fi
}

git_tag_release() {
    local release_version=${1}

    echo "==== Tagging version $release_version"
    git tag -f "v$release_version"
}
