@startuml

title __Asynchronous JMS Communication__

participant "Application" as Application <<Service Provider>>
participant "Simulator" as Simulator <<Service Consumer>>

note over Application, Simulator
Scenario: __NIGHT__
end note
Simulator -> Application : goodNightNotification

@enduml